/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#9d4300",
        "primary-fixed": "#ffdbca",
        error: "#ffb4ab",
        "secondary-container": "#474746",
        "on-tertiary": "#313030",
        "surface-tint": "#ffb690",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed": "#1b1b1c",
        "surface-variant": "#333535",
        surface: "#121414",
        "surface-container-low": "#1a1c1c",
        "tertiary-fixed": "#e5e2e1",
        "on-primary-fixed-variant": "#783200",
        "on-secondary-container": "#b7b5b4",
        "on-background": "#e2e2e2",
        "primary-fixed-dim": "#ffb690",
        "on-surface-variant": "#e0c0b1",
        tertiary: "#c8c6c5",
        "surface-dim": "#121414",
        "on-surface": "#e2e2e2",
        "surface-bright": "#37393a",
        "on-secondary-fixed-variant": "#474746",
        "on-primary": "#552100",
        "surface-container-high": "#282a2b",
        "on-tertiary-container": "#333232",
        "on-primary-fixed": "#341100",
        "tertiary-container": "#9c9a9a",
        "on-tertiary-fixed-variant": "#474646",
        "secondary-fixed-dim": "#c8c6c5",
        "primary-container": "#f97316",
        "on-error": "#690005",
        "tertiary-fixed-dim": "#c8c6c5",
        "on-tertiary-fixed": "#1c1b1b",
        "surface-container-lowest": "#0c0f0f",
        "surface-container-highest": "#333535",
        "on-secondary": "#303030",
        "inverse-surface": "#e2e2e2",
        primary: "#ffb690",
        secondary: "#c8c6c5",
        "surface-container": "#1e2020",
        "secondary-fixed": "#e5e2e1",
        outline: "#a78b7d",
        background: "#121414",
        "outline-variant": "#584237",
        "inverse-on-surface": "#2f3131",
        "error-container": "#93000a",
        "on-primary-container": "#582200",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "touch-target": "48px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        gutter: "16px",
        unit: "4px",
      },
      fontFamily: {
        "data-mono": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "data-mono": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
